js/ui/screenshot.js
src/shell-screenshot.c
src/shell-screenshot.h

Upstream commit: f02b007337e61436aaa0e81a86ad707b6d277378
Fixes:
https://bugzilla.gnome.org/show_bug.cgi?id=699844
[endlessm/eos-shell#2005]

Shell: Limit printscreen button use

---

js/misc/loginManager.js

Make the shell rely again in whatever reply gets from org.freedesktop.login1.Manager.CanSuspend, to decide whether to enable the Alt-based switcher for the power button, which would now show a suspend button if possible, while Alt is pressed.
This PR also fixes the callbacks for org.freedesktop.login1's CanSuspend, CanPowerOff and CanReboot, since they were not considering 'na' as a possible negative answer, when it should be. Otherwise, the blacklisting/whitelisting mechanism implemented in https://github.com/endlessm/systemd/commit/86d4feae5befca7f579f414da19574b17add209e won't work, since 'na' will be the reply that we would be getting in those cases. See https://bugzilla.gnome.org/show_bug.cgi?id=748338 for more details in the bug reported upstream, where only CanSuspend was a …

Make the shell use org.freedesktop.login1.Manager.CanSuspend again

---

tests/Makefile.am

Apparently a real GSettings object is created at some point during the
tests. If the GSettings schema is not installed, for example on a CI
machine, then the tests will fail. This changes the environment to use
the compiled GSettings schema in the local source tree.
[endlessm/eos-sdk#3054]

tests: Use local GSettings schema dir

---

js/ui/layout.js

The existing code accounted for right vs. left hot corner
(taken from the right-to-left support from upstream)
but did not account for top vs. bottom hot corner
(which is not supported upstream at all).
Without this fix, instead of building pressure while pushing
against the bottom-right corner, the pressure would be continually
reset due to an incorrect determination that the corner was being left.
Previously, this case was not hit because the older version of X
did not support pressure barriers.  With the X upgrade, the pressure
barrier was implicitly enabled, and the broken direction check
prevented the hot corner from working anymore.
[endlessm/eos-shell#1325]

Fix pressure barriers for hot corner on bottom

---

data/org.gnome.shell.gschema.xml.in.in
js/ui/layout.js

This feature was implicitly enabled due to the recent Xorg update.
This is not an element of the Endless OS dekstop user experience,
so disable it by default, but make it controllable via a gsetting
so that advanced users can enable the feature at runtime.
[endlessm/eos-shell#5042]

Disable message tray pressure barrier by default

---

jasmine
jasmine.json
tests/Makefile.am

For ease of use, this adds a ./jasmine script that runs all the tests
against the uninstalled code, the same as "make check" does but with a
much more readable output.
Because of technical limitations with setting the mutter typelib dir and
requiring the "run-js-tests" loader, we can't achieve this by simply
executing the "jasmine" command like we do in other packages.
[endlessm/eos-sdk#3171]

Add ./jasmine script to run tests

---

configure.ac
tests/Makefile.am

If we detect a Jenkins environment using the environment variable
JASMINE_JUNIT_REPORTS_DIR that we set in the job's configuration, then
generate XML test reports for each Jasmine unit test.
[endlessm/eos-sdk#3172]

Generate XML reports when running on Jenkins

---

js/ui/shellEntry.js

This will make sure to remove any hint from the entry before the text
gets there.
[endlessm/eos-shell#5104]

shellEntry: grab key focus before pasting

---

js/ui/appActivation.js
js/ui/appIconBar.js
js/ui/workspace.js
js/ui/workspaceMonitor.js
js/ui/workspaceThumbnail.js

The old GJS allowed you to access static methods on an instance of the
class that defined them. Not so with the new GJS. So instead of
any_widget.get_default_direction(), for example, we now must do
Gtk.Widget.get_default_direction(). In this case the offending method
was Shell.WindowTracker.is_window_interesting().
[endlessm/eos-sdk#3265]

Access static method on class, not instance

---

js/ui/components/updaterManager.js

It was determined that the ostree daemon was not upstreamable, so the
interface has moved over to an Endless specific com.endlessm.Updater.
Adjust accordingly.
[endlessm/eos-shell#5087]

updaterManager: Adjust to new dbus interface

---

debian/changelog
debian/control

The debian packaging derives the install directories from the source
package name. When this changed to eos-desktop, some files moved to
places the autotools didn't install them to since the module name is
still eos-shell. This caused some required files to be lost from the
binary packages.
[endlessm/eos-shell#5208]

Change source package name back to eos-shell

---

js/ui/appDisplay.js

Differently from the desktop icon, the search icon code would not check
whether the application is already running before activating the splash
screen.
Consolidate this code in a separate function and call it from both
places.
This fixes a bug where the splash screen would appear for running
applications when launched from the search results.
[endlessm/eos-shell#5209]

appDisplay: consolidate code for app icons activation

---

js/ui/appFavorites.js

eos-theme has hardcoded eos-app- prefixes in this key for a long time,
which is not desired. If there are still eos-app-* values in the key,
strip them out, since we don't ship those desktop files anymore.
[endlessm/eos-shell#5272]

appFavorites: strip out eos-app- prefixes

---

src/shell-app-system.c

When g_app_info_delete() is called, such as when removing a custom
launcher from the desktop, GIO will set the desktop ID field of the
GDesktopAppInfo to NULL automatically.
That breaks an assumption in ShellAppSystem that g_app_info_get_id()
does not change over the lifecycle of a GAppInfo. When iterating over
the app infos in response to a GIO change, we'll segfault when we hit
the deleted application.
This commit fixes the issue explicitly checking for g_app_info_get_id()
returning NULL after a change from the GAppInfoMonitor.
[endlessm/eos-shell#5379]

ShellAppSystem: fix a crash when removing custom desktop files

---

js/ui/unlockDialog.js

Since the keystroke that wakes the screensaver is applied to the
unlock dialog, if the user tries to use the Esc key to exit the
screensaver (which is one of the most intuitive keys to do so),
the dialog is immediately canceled by this single Esc keystroke.
In the future, we may want to block the wake-up keystroke from
being applied to the password, in which case we could revert
this commit and re-enable the Esc key to cancel the dialog.
[endlessm/eos-shell#5213]

Unlock: do not map Esc key to Cancel

---

js/ui/appActivation.js

This prevents a situation where the speedwagon's window would cause the
DesktopAppClient instance to reset the _lastDesktopApp value in between
the actual app has been launched and its window shown, preventint it
from getting maximized properly.
[endlessm/eos-shell#5377]

appActivation: Ignore splash screens on the _windowCreated callback

---

Makefile.am
m4/eos-coverage.m4
tests/Makefile.am

Not ready for merging yet.
eos-desktop is still tricky because of the use of recursive make. I've tried to remove the redundant rules and just embrace the recursiveness by making `coverage-lcov` and `coverage-cobertura` rules that just forward on to `tests/Makefile`.
For some reason adding `run_coverage.coverage` and even `tests/run_coverage.coverage` to `CLEANFILES` doesn't get it added to the list of stuff removed on `distclean` so I've had to add a separate rule for it.
[endlessm/eos-sdk#3303]

Update eos-coverage.m4 and add coverage test

---

src/shell-app.c

Instead, wait for the app to transition to the RUNNING state before
clearing it out. Otherwise, after the user clicks the X on the splash
window, then the application would transition to STOPPED, which means
that we won't track when the application starts for real and try to
quit it.
[endlessm/eos-shell#5410]

appActivation: Don't clear the splash immediately when cancelled

---

configure.ac
data/Makefile.am

By default these keybindings install systemwide and it doesn't
make sense to change their install location. Requiring root access
to run make install is not desirable and so the user
should have been able to disable this.
[endlessm/eos-shell#5439]

Makefile: Allow disabling of keybindings installation

---

js/ui/components/updaterManager.js

Instead of going through gnome-session.
[endlessm/eos-shell#5591]

updaterManager: reboot directly from notification

---

js/ui/panel.js

It's not at the top anymore.
[endlessm/eos-shell#5320]

panel: change name of panel to Taskbar in Ctrl+Alt+Tab

---

js/ui/viewSelector.js

The metrics query must be updated when the search provider enum is
added to.
[endlessm/eos-sdk#3609]

Add link in documentation to metrics query.

---

js/ui/appActivation.js

Previously we would always show a splash screen for weblinks, and
dismiss it after 700ms, regardless of whether the browser was running or
not. This does not match the behavior of any other launcher, which will
show the splash screen when the underlying application isn't running and
will not show it otherwise.
Change the special case logic we have for weblinks to implement the same
behavior for those launchers.
[endlessm/eos-shell#5547]

appActivation: use a different special case for eos-link launchers

---

js/ui/shellDBus.js

Previously, it was not possible to remove an application from the store
that was not on the desktop.
Now that we have an "installed apps" page in the app store, this
operation is possible, and the app store will call into this DBus
method to make sure the desktop icon is deleted when an application is
removed.
In such case, we should not mark the operation as "interactive",
otherwise we'll get a shell notification with an Undo button that is not
intended.
While it's not exercised by the app store at the moment, also change the
same code for folder icons.
[endlessm/eos-shell#5836]

shellDBus: don't mark remote method calls as interactive

---

js/ui/appIconBar.js

We now ensure that other menus and window lists are closed before
showing the right-click menu to ensure we don't get strange menu stacking
visual artifacts.
[endlessm/eos-shell#3962]

Shell: Fixed right-clicking eventing on the task bar

---

src/shell-global.c

All current code assumes that the list of window actors corresponds to the
list of windows; however as the list returned by meta_get_window_actors()
now includes actors during the destroy animation, that assumption breaks.
Eventually we should make everyone move to a more appropriate API, but
for now make it work again by returning a filtered list of "good"
window actors.
https://bugzilla.gnome.org/show_bug.cgi?id=735927
[endlessm/eos-shell#5575]

global: Filter out destroyed actors from get_window_actors()

---

js/gdm/loginDialog.js

Previously when we would enter the password wrong too many times, the
user would get cleared an our hint-showing logic would break so now we
explicitly check that the value is there.
[endlessm/eos-shell#5930]

Shell: Fixed crash of login scripts when we exceed maximum login attempts

---

data/theme/gnome-shell.css

So that it responds to e.g. Large Text.
[endlessm/eos-shell#5952]

theme: use points instead of pixels to set search entry font size

---

data/Makefile.am

cosimoc:  mcatanzaro, on second thought I don't think the rules file
should go in /etc/polkit-1/rules.d
cosimoc:  should go into /usr/share/polkit-1/rules.d instead
cosimoc:  it's not a distributor override - that's what the /etc rules
are for AFAIU
[endlessm/eos-shell#4681]

Move 40-gdm.rules to $(datadir)

---

js/ui/workspaceMonitor.js

The rationale is in the code comment.
[endlessm/eos-shell#5970]

workspaceMonitor: special case speedwagon windows

---

js/ui/dateMenu.js

When dealing with the composite mode, the screen's scale
factor is such that the calendar popover is bigger than
the entire screen.
Fix that by simply adding scrollbars when the popover is
too big to fit the screen.
[endlessm/eos-shell#5926]

dateMenu: add scrollbars when calendar is too big

---

js/ui/status/network.js

Add the wifi icons in a end-aligned StBin so they are correctly positioned. This is the same approach taken to fix the power menu alignment.
[endlessm/eos-shell#6154]

network: fix wifi icons alignment

---

js/ui/status/network.js

We need the icons box to span all the way to the end.
[endlessm/eos-shell#6154]

network: fix network icon alignment

---

js/gdm/loginDialog.js

Not really sure the distinction between single quotes and double quotes
makes sense, but let not me be the one to have messed it up.

loginDialog: Use single quotes for non-translatable strings

---

js/ui/appDisplay.js

When removing an application and quickly adding it again sometimes the icon
would not be added back again because there would be no apparent changes
in the icon list. To avoid this, these changes update the icon list before
the animation and subsequent icon addition.
[endlessm/eos-shell#5849]

Fix icon grid when quickly removing+adding app

---

js/ui/appDisplay.js

The app folder's close button is positioned on the top right of the
folder's boxPointer. However, when the boxPointer has its arrow on
top (when the folder pops downwards), its box will be positioned lower
and thus the close button appears a bit higher than it should be.
These changes fix that problem by placing the close button taking
into account the position of the boxPointer.
[endlessm/eos-shell#6263]

appDisplay: Fix app folder close button's position

---

data/theme/gnome-shell.css
js/ui/dateMenu.js
js/ui/popupMenu.js

This PR does three things:
* Fixes a small bug I found around while looking at the code (Jasper's commit)
* Makes sure that the popups get adjusted in size and show the relevant scrollbars when needed
* Slightly adjust the CSS for popups so that horizontal rules are as close to the edge as vertical ones
[endlessm/eos-shell#6308]

Show horizontal scrollbars for PopupMenu when needed

---

js/ui/dateMenu.js

dateMenu: use new desktop name for gnome-clocks

---

js/ui/appDisplay.js

This reverts commit 98f8ae1611e8c70b7a6a4048370e593beb46152f. The reason
is that those changes were introduced to fix an issue in the icon grid
which no longer happens.

Revert "Fix icon grid when quickly removing+adding app"

---

js/ui/appDisplay.js
src/shell-app-system.c
src/shell-app-system.h

These changes add a DBus method to make the desktop aware that something about an application's desktop info has changed and, currently, uses that trigger to re-read an app's desktop info and update its icon in the desktop.
The use case is a weblink that can be added to the desktop before its favicon has been retrieved; thus, once the favicon has been downloaded and the desktop file changed, the app icon will be updated o the desktop with these changes.
[endlessm/eos-shell#4920]

Add a way to update an app's desktop info

---

js/ui/overview.js
js/ui/workspaceMonitor.js
src/shell-app-system.c
src/shell-app-system.h
src/shell-app.c

These changes reimplement the workspace monitor and base the logic on apps' events instead of windows's events.
[endlessm/eos-shell#4190]

Reimplement workspace monitor

---

js/gdm/loginDialog.js

JS WARNING: [resource:///org/gnome/shell/gdm/loginDialog.js 1174]:
anonymous function does not always return a value
No behavior change, just silencing the warning.
[endlessm/eos-shell#6352]

loginDialog: Fix gjs warning

---

src/st/st-entry.c

Should only allow pasting the primary selection when the entry is
editable.
[endlessm/eos-shell#6384]

st-entry: Disable middle-click-paste when entry is not editable

---

src/shell-app.c

Instead, track the number of speedwagon windows, in addition to the
regular logic, to decide if we should move to the STARTING state.
At the same time, make it possible to transition from STARTING to
STOPPED following the same logic.
[endlessm/eos-shell#6018]

ShellApp: don't transition to STARTING state from launch

---

js/ui/appActivation.js
js/ui/appIconBar.js
js/ui/windowAttentionHandler.js
js/ui/windowManager.js
src/shell-app.c
src/shell-window-tracker.c
src/shell-window-tracker.h

The last commit in the PR is not so much related to the issue that it tries to solve but just replaces the check for the speedwagon by the function added in the window-tracker which makes the code a lot cleaner.
T6408

Prevent the speedwagon from showing in the icon menu

---

js/ui/screenShield.js

There's no value in doing this. Upstream doesn't do it. It breaks
password reset via email, except in the case the user manually moves
the mouse or presses a key every five minutes to keep the screen from
blanking.
https://phabricator.endlessm.com/T10864

screenShield: Do not reset login screen in greeter mode

---

src/shell-network-agent.c

In get_secrets_keyring_cb, we own a ref on the 'attributes' hash table
from secret_item_get_attributes), and a ref on the 'secret' object (from
secret_item_get_secret(), but in the SHELL_KEYRING_SK_TAG case, we unref
these once before breaking out of the loop, and the second time after
breaking out of the loop.
https://phabricator.endlessm.com/T10828

NetworkAgent: Fix double-unref in get_secrets_keyring_cb()

---

js/ui/workspace.js

When dealing with unmapped actors, Shell crashes since
St cannot create a theme node and ends up crashing. It
affects important applications such as eos-tutorial.
The proposed solution introduced another issue when an
unmapped window shows up since it completely aborts the
positioning code, which is something we want to do in the
majority of cases.
This commit places the check for unmapped windows before
adding the window, which fixes both the crash and the hot
corner issue.
https://phabricator.endlessm.com/T11146

workspace: properly check for unmapped actors

---

js/ui/viewSelector.js

This commit is a workaround on the Clutter misbehavior with
Framebuffer Objects. Precisely, the clone won't update properly
because the original actor mistakenly doesn't detect the living
clone and doesn't update correctly.
Fix that by adding a redraw'ing routine in an idle, to give
time for the original actor to update.
https://phabricator.endlessm.com/T5950

viewSelector: redraw the clones on large text setting changes

---

src/shell-recorder-src.c

Use the do-timestamp feature of basesrc to place the correct timestamp on each outgoing buffer.
This makes eos-shell's screen recorder work again, preventing it from specifying bogus values for the desired framerate for encoding videos with the vpx codecs, via the gst-plugins-good's libgstvpx plugin.
Patch backported from upstream: https://git.gnome.org/browse/gnome-shell/commit/?id=43ae3b81
https://phabricator.endlessm.com/T10862

shell-recorder-src: use timestamping from basesrc

---

js/ui/viewSelector.js

The current allocation code queries the allocation of
two different actors (the icon grid and the all view
itself) to calculate the sizing of the apps grid page
layout.
The problem with this approach is when the icon grid
outputs a size different than the all view actor, leading
to a miscalculation and making the search entry be
positioned wrongly.
Fix that by only calculating the size of the all view
actor.
https://phabricator.endlessm.com/T6047

allView: consistently calculate the all view height

---

src/st/st-texture-cache.c

If a given icon is not available for neither the current theme nor any
of the fallback options (default theme -"Adwaita", "gnome"...), the
call to gtk_icon_theme_lookup_by_gicon() will return a NULL value, which
returned by the Shell Toolkit as is, causing trouble in the Shell's JS
code when calling shell_app_create_icon_texture() to create an icon.
To at least mitigate the chances of this having this issue happening, we
should at least try to load the standad 'image-missing' icon from the
Icon Naming Specification spec when we receive a NULL here, so that
at least we try to show something to the user, even if it's ugly.
Upstream issue: https://bugzilla.gnome.org/show_bug.cgi?id=766391
https://phabricator.endlessm.com/T11550

Load fallback image-missing image when no other icon was loaded

---

js/ui/appDisplay.js

That item is special and does not have a get_app_info function like the
others.
https://phabricator.endlessm.com/T11785

appDisplay: Prevent error when checking for changes in the 'More apps…' item

---

js/ui/iconGrid.js

With clutter 1.26, ClutterText will never propagate button press events
if it is selectable. We don't actually need our ClutterText to be
selectable except when we are in edit mode, so keep the editable and
selectable properties in sync. This fixes a regression caused by clutter
1.26 where it became impossible to rename desktop icons.
https://phabricator.endlessm.com/T12228

iconGrid: sync editable and selectable properties of ClutterText

---

js/ui/main.js

WorkspaceMonitor connects to a bunch of signals that depends
on the window manager. These signals are not synchronized in
any way with the rest of the codebase.
Given a fast-enough initialization, the WorkspaceMonitor instance
can try to load the overview before the overview is ready, since
both the overview and the layout manager are initialized after
WorkspaceMonitor.
Fix that by initializing the layoutManager and overview before
the WorkspaceMonitor, ensuring that we always have a valid overview
to animate.
https://phabricator.endlessm.com/T12522

main: initialize layout manager before workspace monitor

---

configure.ac
data/org.gnome.shell.gschema.xml.in.in
js/ui/windowManager.js
src/Makefile.am
src/wobbly-effect.cpp
src/wobbly-effect.h

Link to libwindowfx_wobbly (from libwobbly) and add a new
EndlessShellFXWobbly class to bridge between a clutter effect
and the wobbly::Model/wobbly::Anchor.
Use endless_shell_fx_wobbly_grab to grab a point on the mesh
and move it around.
Use endless_shell_fx_wobbly_ungrab to release a point on the mesh.
Each of the above functions may only be called once whilst in the
opposing state and cannot be called again whilst in the same state.
EOSShellWobbly is a JavaScript subclass of EndlessShellFXWobbly
which handles integration between the shell itself and the wobbly
effect. It provides API to handle mouse grab / ungrab of a window
and window movement whilst grabbed.
Provide the following new keys in org.gnome.shell:
'wobbly-spring-k' : Spring K
'wobbly-spring-friction' : Spring Friction …

Mission: Add wobbly windows.

---

src/shell-js.cpp

This removes all usage of SpiderMonkey API that is deprecated in mozjs24
and will be removed in mozjs31.
https://bugzilla.gnome.org/show_bug.cgi?id=742249
https://phabricator.endlessm.com/T13537

shell-js: Remove usage of deprecated API

---

data/org.gnome.shell.gschema.xml.in.in
js/gdm/loginDialog.js

The password reset feature is only desired on Endless hardware, not on
the free downloadable images nor on OEM images. Image type is determined
by checking the eos-image-version xattr of /sysroot. A gsetting is
provided to override the default behavior. (Note that the gsetting has
to be set for the gdm user, not your own user account.)
https://phabricator.endlessm.com/T13460

Disable password reset except on Endless hardware

---

src/shell-window-tracker.c

Our window matching currently fails frequently with Flatpak
applications, as one of the primary hints used to link windows
with .desktop files - the WM_CLASS - no longer matches when
flatpak renames the exported .desktop file. Worse, as Flatpak
applications are run in their own PID namespace, different
apps frequently share a common _NET_WM_PID, resulting in
unrelated apps being grouped together by one of the fallback
paths. To match Flatpak applications reliably, take the newly
exported Flatpak ID into account.
https://bugzilla.gnome.org/show_bug.cgi?id=772615

window-tracker: Consider Flatpak ID for window matching

---

js/misc/eos-launch.js

We use dots now instead of hyphens. Fix eos-launch to also use dots, or
it will always fail when launching applications.
https://phabricator.endlessm.com/T12576

eos-launch: fix for new application IDs syntax

---

js/ui/iconGridLayout.js

Variables can't be used as key names in literals like this (barring some
futuristic syntax I don't think our gjs supports yet), so the fallback
previously used the literal key 'DESKTOP_GRID_ID' rather than its value,
'desktop'.
Found while working on https://phabricator.endlessm.com/T12548

iconGridLayout: fix fallback when no defaults found

---

data/theme/gnome-shell.css
js/ui/viewSelector.js

In order to compensate the blank pixels around the icons - which
we can't remove -, also consider the margin-top CSS property to
calculate the height of the search entry.
https://phabricator.endlessm.com/T4924

theme: add top margin to the search entry

---

src/Makefile.am

Defining this means that automake will not calculate it automatically
(https://www.gnu.org/software/automake/manual/automake.html#Linking). In
particular, this means that make will not wait until libeos-shell-js.la
libeos-shell-fx.la have completed before trying to link eos-shell-real.
Since libeos-shell-fx.la is a C++ library, it's likely that it won't be
complete before make schedules the eos-shell-real link.
Automake will add all the LDADD objects to DEPENDENCIES itself, and
everything will be fine. You really only want to be defining
DEPENDENCIES yourself in special cases.

build: Remove eos_shell_real_DEPENDENCIES

---

js/ui/appDisplay.js

This reverts commit 8c4ae335b51ab4b141f7580e5c0779fccae266f4.
This was actually marked as CR fail earlier, because it broke hovering over the trash can, but I didn't check phabricator before looking at the code.
https://phabricator.endlessm.com/T13331

Revert "appDisplay: sync/set hover on the right actor"

---

js/ui/appIconBar.js

Otherwise, if two apps happen to share the same PID (e.g. because one is
a Chromium web app, which has the same PID of Chromium), it will end up
being discarded.
https://phabricator.endlessm.com/T13809

appIconBar: don't use a Hash.Map to index apps by PID

---

js/ui/appDisplay.js

This code path will be hit when an icon is dragged outside of the view
boundaries.
https://phabricator.endlessm.com/T13331

appDisplay: unset drag hover state when resetting drag view

---

js/ui/appDisplay.js

Instead of always calling it from _resetDragViewState() which is called
from multiple locations, call it from where we were hitting the
bug in the first place.
https://phabricator.endlessm.com/T13331

appDisplay: be more careful when resetting drag hover state

---

js/misc/util.js

The fallbak to chromium might be overkill, somethings gone pretty
wrong with eos if there's no app associated for web, but it can't
hurt
https://phabricator.endlessm.com/T13873

util: don't hardcode browser app

---

src/shell-app-system.c

This fixes the shell not picking updates to the contents of the underlying `.desktop` files for application launchers, or when a `.desktop` file is overriden by a user-installed one under `~/.local/share/applications`.
A direct backport from the upstream patch was not possible, so this is an adaptation of the patch for GNOME Shell which fixes [bug #773636](https://bugzilla.gnome.org/show_bug.cgi?id=773636).
https://phabricator.endlessm.com/T14057

Properly detect changes in .desktop files

---

src/run-js-test.c

This will be required in the upcoming version of GJS.
https://bugzilla.gnome.org/show_bug.cgi?id=775374
https://phabricator.endlessm.com/T14460

tests: Destroy GjsContext before exit

---

js/ui/codingManager.js

Pass the manifest of the application to GNOME Builder to
construct the workbench for the application source. Concatenate
an override app-id that will be used to launch the modified app
so that there are no conflicts with the already running
application. The application itself needs to set the
G_APPLICATION_CAN_OVERRIDE_APP_ID flag in order for this to
work.

CodeView: launch GNOME Builder with the manifest of the application

---

js/ui/codingManager.js

We only should try to associate a Builder window with
a coding session if a coding session exists T14671.

Coding: being able to run GNOME Builder outside of a coding sesssion

---

src/run-js-test.c

In the upcoming version of GJS, the gjs/coverage.h header disappears, and
GjsCoverage is available through the public API in gjs.h.
The constructor gjs_coverage_new_for_cache() disappears as well; the only
public constructor is gjs_coverage_new(), which puts the cache file in a
default location.
https://phabricator.endlessm.com/T13622

tests: Adapt to new GjsCoverage API

---

js/ui/codingManager.js

When the desktop is shown and the windows are hidden and vice
versa we need to make sure the overlay buttons are hidden and
shown again in those cases. The overview emits signals for
those cases used at other places in the shell already.
In the handlers we do not try to figure out the current active
session window and hide/show the existing buttons in any case.
https://phabricator.endlessm.com/T14811

CodeView: listen to overview hiding and showing to hide overlay buttons

---

js/ui/iconGridLayout.js

If the setting describing whether Google Chrome should be installed on
start up is enabled, then we replace Chromium's icon by Chrome's as it
will become the default browser.
https://phabricator.endlessm.com/T15084

iconGridLayout: Replace Chromium's icon by Chrome when needed

---

js/ui/iconGridLayout.js

This schema will not be installed on all possible configurations, and
specially not on ARM, so we need to check for its existance before
using it, instead of assuming it's always there.
https://phabricator.endlessm.com/T15084

Treat the 'com.endlessm.GoogleChromeInitialSetup' schema as optional

---

js/ui/userWidget.js

UserWidget instances should be destroyed when the actor is. That's
what consumer code expects since the destroy() method is never called.
https://bugzilla.gnome.org/show_bug.cgi?id=700807
https://phabricator.endlessm.com/T12270
---
Backported (no changes required) from [upstream](https://bugzilla.gnome.org/show_bug.cgi?id=700807) to fix the same problem as in PR #219.

userWidget: Fix leaking instances

---

js/ui/iconGridLayout.js

When no icon layout is configured, then the default values are used but
never stored which means that the logic for getting the default values
will be executed again (until the gsetting for the layout is modified).
This may be a problem because what the user saw after logging in may not
be what will be shown the next time they start a session:
e.g. we are replacing the Chromium icon by the Google Chrome one
dynamically in the list of default icons; this logic is based on a
gsetting so, if we do not store that default configuration and the
mentioned gsetting is changed, the list of icons may be different next
time the user starts the session.
This patch always makes sure that the default grid of icons is also
stored and not simply shown, to ensure consistency in every reboot. …

iconGridLayout: Store layout after using defaults

---

js/ui/appFavorites.js

Similar to what we did for the icon grid, we want the default favorites
(e.g., the taskbar pins) to substitute chrome for chromium if we have
the integration enabled, and we save the modified settings so that
the configuration remains after chrome has been installed (which clears
the gsetting for the chrome initial setup integration).
https://phabricator.endlessm.com/T15296

appFavorites: handle automatic google-chrome integration

---

js/ui/iconGridLayout.js

By adding a JSON file in /var/eos-image-defaults/icon-grid,
the default icon grid for a locale can be overridden.
For instance, this allows the image builder to specify
having Chrome on the desktop by default rather than Chromium.
Follows the same syntax and locale-matching of the defaults in
/usr/share/eos-shell-content/icon-grid-defaults.
If there is any image default override that matches the user's locale,
it will take priority over any base default, even if the base default
is a more specific match to the user's locale.
Any image default prepending or appending is still applied
after this override.
https://phabricator.endlessm.com/T15324

iconGridLayout: add image default override option

---

js/ui/iconGridLayout.js

This makes the default simply an empty icon grid, avoiding a crash if the
icon grid files are not present.
https://phabricator.endlessm.com/T15606

iconGridLayout: Provide default for missing icon grid files

---

src/shell-util.c

Instead of returning NULL. The function is documented as returning an
empty string on errors, and since StLabel does not support setting a
NULL text, this will prevent a crash in that case.
https://phabricator.endlessm.com/T15657

util: return an empty string when format string is malformed

---

js/ui/components/updaterManager.js

A few updates to `updaterManager.js` to avoid showing failure notifications on dev-converted systems, and to load the new eos-updater configuration files.
https://phabricator.endlessm.com/T15644

T15644 update errors

---

js/ui/messageTray.js

If we don't, we will pop up the summary again the next time
_updateState() is called.
https://bugzilla.gnome.org/show_bug.cgi?id=707600
https://phabricator.endlessm.com/T15855

messageTray: Reset clickedSummaryItem on ungrab

---

data/theme/gnome-shell.css
js/ui/background.js

Use a darker, more blue color to match the new plymouth theme
for startup and shutdown screens.
https://phabricator.endlessm.com/T15693

Update background color

---

data/theme/gnome-shell.css

The search entry is 6px misaligned (again). Fix that by increasing
the margin-top CSS property.
https://phabricator.endlessm.com/T15536

searchEntry: fix vertical placement

---

data/gnome-shell-theme.gresource.xml
data/theme/process-working-dark.svg
js/ui/shellEntry.js

After the introduction of the new searchbar style,
the spinner became almost invisible since it's white
over the new white background.
Fix that by adding a new dark spinner, and using it
on the desktop search bar.
https://phabricator.endlessm.com/T15536

searchEntry: fix white spinner

---

js/ui/components/updaterManager.js

This was a fallout from previous backports; addButton() now directly
takes a callback.
https://phabricator.endlessm.com/T16001

updateManager: fix update notifications

---

js/ui/components/updaterManager.js

eos-updater will not update a live-booted system, so do not show errors
from it saying the system is live booted.
Signed-off-by: Philip Withnall <withnall@endlessm.com>
https://phabricator.endlessm.com/T15977

updaterManager: Ignore errors from running on live booted systems

---

js/ui/shellDBus.js

Sometimes we need to make sure an application is visible in the
desktop's grid (i.e. in its top level folder) but without forcing
an append of its icon because if the app is already visible it should
not move to the end of the grid.
For that reason a new AddAppIfNotVisible method is added to the DBus
interface which will only add the given app to the desktop if it's not
already there and visible.
https://phabricator.endlessm.com/T15941

Add a DBus method to add an app only if it's not visible

---

js/ui/codingManager.js

Windows are set to be showing after the maximization state changes
which breaks the illusion. Hide the relevant window
https://phabricator.endlessm.com/T16087

coding: Hide/show windows after unmaximization

---

js/ui/notificationDaemon.js

Pressing the notification when the overview was in front of all the
non-minimized windows of other applications didn't result in the
application window being shown. Hide the overview explicitly then.
https://phabricator.endlessm.com/T16208
This looks a bit like a blunt way to hide the overview, but I noticed that there was a prior art in fdo notifications handling, so I followed suit.

messageTray: Hide overview on notification activation

---

js/ui/codingManager.js

We want to pull in the upstream version instead of
our custom endless one. Part of T16393
This basically reverts: a6de674cfc6547ee024b6afdcde47593285449cc

CodeView: use the flatpakID for upstream GNOME Weather

---

configure.ac
js/ui/windowManager.js
src/Makefile.am
src/shell-global.c
src/shell-slicer.c
src/st/st-box-layout.c
src/st/st-theme-node-drawing.c

A few small changes are required now that mutter bundles its own private and newer versions of cogl and clutter, so that eos-shell can find and use the right libraries and APIs. 
https://phabricator.endlessm.com/T16276

Adapt eos-shell 3.8 to build and run on top of mutter 3.22 

---

js/ui/appDisplay.js
js/ui/iconGrid.js

This is the reason why we have a hack in animateShuffling() to force
a repaint of the main view right before animating the icon, which we
can't use anymore as it relied in some undefined behaviour in clutter
that is no longer working as "expected", and now crashes the shell.
Besides, there is no need to artificially add the icon to the main view
when dragging it from inside a folder into the main grid layout, as it
will be inserted anyway in IconGridLayout.layout.repositionIcon.
Also, artificially adding that icon to the list really confused the logic
that finds out which icons need to be moved in the icon grid, which unmasked
a bug during the animation only visible after removing the call to paint(),
so this is seems to be also cleaner now.
https://phabricator.endlessm.com/T16707

Don't prematurely add an icon coming from a folder to the main view
