endlessm/eos-desktop

data/eos-session.desktop.in.in
=> eos-session: Add Endless to XDG_CURRENT_DESKTOP

js/ui/search.js
=> search: never query providers with empty query

js/ui/appFavorites.js
=> appFavorites: update dash on app install/remove

js/ui/background.js
=> background: default backgrounds have moved

debian/eos-shell.install
Hopefully fixes password reset
=> Install 40-gdm.rules

js/gdm/loginDialog.js
Otherwise it looks nonsense in Arabic locales.
[endlessm/eos-shell#6055]
=> loginDialog: Force telephone number to display LTR

data/org.gnome.shell.gschema.xml.in.in, js/ui/appFavorites.js, js/ui/appIconBar.js, js/ui/popupMenu.js
=> Allow pinning apps to the taskbar

js/ui/appActivation.js
When the overview is hidden, the actors corresponding to visible
(non-minimized) windows are shown. As a result, the speedwagon's
animation does show up as smooth as it should.
These changes hide the mentioned actors while the speedwagon is shown
and show them again just before the speedwagon disappears. This way the
speedwagon's animation is smooth and there is no impact on the behavior
after it is gone.
https://phabricator.endlessm.com/T5419
=> appActivation: Prevent showing windows before speedwagon

js/ui/iconGridLayout.js
Like we do when building the list of favorites.
[endlessm/T6387]
=> iconGrid: Lookup aliased app ids when building the grid

js/ui/workspace.js
https://phabricator.endlessm.com/T3727
=> Never crash when launching eos-tutorial

data/org.gnome.shell.gschema.xml.in.in, js/ui/status/social.js
https://phabricator.endlessm.com/T11619
=> panel: Show/hide the social bar icon depending on a gsetting

js/ui/background.js
https://phabricator.endlessm.com/T10782
=> background: remove support for reading eos:///default

data/org.gnome.shell.gschema.xml.in.in
Instead of just the browser, we want the following (from left to right):
- app center
- browser
- file manager
https://phabricator.endlessm.com/T13086
=> Change default pinning

js/ui/magnifier.js
This was lost in commit 2bc4b58df56b675861e43bf3c38fa9dd33065dee while
rebasing.
https://phabricator.endlessm.com/T13033
=> magnifier: add missing import

js/ui/appDisplay.js
This was lost in a rebase a while ago.
https://phabricator.endlessm.com/T13331
=> appDisplay: sync/set hover on the right actor

data/org.gnome.shell.gschema.xml.in.in, js/js-resources.gresource.xml, js/ui/components/missionChatbox.js, js/ui/components/missionGameService.js, js/ui/main.js, js/ui/panel.js, js/ui/sessionMode.js, js/ui/sideComponent.js, js/ui/status/missionGame.js, js/ui/windowManager.js
https://phabricator.endlessm.com/T12729
=> T12729 squashed

data/org.gnome.shell.gschema.xml.in.in, js/js-resources.gresource.xml, js/ui/components/codingGameService.js, js/ui/components/codingManager.js, js/ui/main.js, js/ui/panel.js, js/ui/sessionMode.js, js/ui/status/codingGame.js
Rename the occurrences of mission to coding, including the
GSettings key. Part of T13797.
=> Rename mission to coding

js/ui/status/codingGame.js
When coding manager button is pressed, the icon bounces the same way
as it does in the icon bar.
https://phabricator.endlessm.com/T13824
=> coding: add icon bounce

js/ui/components/codingGameService.js
Instead of connecting to showmehow-service, connect to coding-game-service.
We have two events, one for when a window was moved and one for when a window has not been moved in a particular period.
https://phabricator.endlessm.com/T13613
=> coding: Connect to coding-game-service and listen for events there

js/ui/appDisplay.js, js/ui/iconGrid.js, js/ui/main.js, js/ui/messageTray.js, js/ui/notificationDaemon.js, js/ui/overview.js, js/ui/screenShield.js, js/ui/status/bluetooth.js, js/ui/status/network.js, js/ui/windowAttentionHandler.js, src/shell-global.c, src/shell-global.h
https://phabricator.endlessm.com/T13823
=> Backport gtk notifications from upstream and add badges to the desktop icons

js/extensionPrefs/main.js
https://phabricator.endlessm.com/T14161
=> Backport extensionPrefs application

js/ui/appDisplay.js
https://phabricator.endlessm.com/T14362
=> appDisplay: Show an icon badge only for chatbox app

js/ui/appDisplay.js
https://phabricator.endlessm.com/T14361
=> appDisplay: Filter coding apps when the game is disabled

data/eos-shell-extension-prefs.desktop.in.in
Also, change the name so it's not too long and use a reasonable icon.
https://phabricator.endlessm.com/T14161
=> Display Extension Preferences app

data/eos-shell-extension-prefs.desktop.in.in, js/extensionPrefs/main.js
https://phabricator.endlessm.com/T14161
=> data, js: remove GNOME references

po/zh_HK.po, po/zh_TW.po
=> A few Chinese edits

src/gnome-shell-extension-prefs.c, src/main.c, src/shell-global-private.h, src/shell-global.c
https://phabricator.endlessm.com/T14460
=> Clean up ShellGlobal before exit

src/run-js-test.c
https://phabricator.endlessm.com/T13622
=> tests: Fix argument order

js/Makefile.am, js/misc/config.js.in, js/ui/iconGridLayout.js
https://phabricator.endlessm.com/T14481
=> Enable support to merge prepend/append JSON files into the icon-grid

js/ui/appActivation.js
If there is an issue with launching an application for which a
speedwagon has been shown, and that application only reports that it
is starting, then the speedwagon stays on forever, showing on top of
other apps which hinders UX.
This is the case for Google Chrome when it is not installed. In that
case, Google Chrome's icon launches the App Center instead, but since
the browser's own window is never shown -- so there's no state
transition for the shell to hide the speedwagon -- and the speedwagon
stays on forever.
This keeps the previous behavior of managing the speedwagon based on
its app's state but also hides it if the focused app is changed and
does not match the speedwagon's one.
https://phabricator.endlessm.com/T15129
=> Hide speedwagon when the focused app changes

js/ui/components/codingGameService.js
https://phabricator.endlessm.com/T13630
=> codingGameService: Use CodnigGameService.AppIntegrationController

js/ui/internetSearch.js
A couple of fixes for JSON parsing in `internetSearch.js`.
https://phabricator.endlessm.com/T15172
=> T15172 fix json parsing

js/misc/ibusManager.js, js/misc/keyboardManager.js, js/ui/windowManager.js, src/gnome-shell-plugin.c, src/main.c
https://phabricator.endlessm.com/T15554
=> Prepare eos-desktop for SpiderMonkey 38

js/ui/codingManager.js
https://phabricator.endlessm.com/T14628
=> CodeView: use D-Bus activation for starting up the gnome-builder

js/ui/components/updaterManager.js
https://phabricator.endlessm.com/T15644
=> T15644 update notifications

js/ui/appActivation.js, js/ui/codingManager.js, js/ui/windowManager.js
https://phabricator.endlessm.com/T15681
=> T15681 Additional refactoring with button animations

js/ui/components/codingGameService.js
https://phabricator.endlessm.com/T16114
=> coding: Reduce timeout for wobbly_window demo to 2500

js/ui/codingManager.js
This will allow us to keep the minimum size of both windows in
sync.
https://phabricator.endlessm.com/T15968
=> coding: Bind to geometry-allocate and attempt to constrain resizes

js/ui/sideComponent.js, js/ui/windowManager.js
https://phabricator.endlessm.com/T16425
=> Adapt to rename of GrandCentral to DiscoveryFeed

js/ui/iconGridLayout.js
https://phabricator.endlessm.com/T15704
=> move eos-image-defaults to /var/lib
